### ISSUE TITLE
not imported 'tot_psf' in psfmodels.__init__

### ISSUE THREAD

**Issue by ZhenhongDu** [tlambert03/PSFmodels#6]
* psfmodels version: latest version
* Python version: 3.8
* Operating System: Windows 10

### Description
Recently, I installed PSFmodels on a new computer, and I found that the function 'tot_psf' were not imported in the psfmodels.__init__function, so when I used 'psf.tot_psf function', there was a mistake.  I added it by myself.  Did you forget it?

[not imported in psfmodels.__init__](https://github.com/tlambert03/PSFmodels/blob/00a275947dd0d762fa0632b6167bd40ac769be27/src/psfmodels/__init__.py#L16)

**Comment by dzh929** [comment]
By the way, I want to ask that the NA value used in `ex_lens = {**air_lens, 'NA': 0.01}` is the illumination objective NA?  In general, the illumination objective NA of our system does not fill the whole back focal plane. Should I use the reduced NA?

**Comment by tlambert03** [comment]
sorry about that, I removed it from the top level since I'm not sure how robust it is.  I can add it back (but definitely use with some degree of caution and double check the source).  You can still import it at 

```python
from psfmodels._core import tot_psf
```

> In general, the illumination objective NA of our system does not fill the whole back focal plane. Should I use the reduced NA?

yep, any NA entered into a field here should be assumed to be the "effective" NA.  If you use an iris or otherwise don't fill the BFP, your effective NA is lower than the nominal NA on the objective.

**Comment by dzh929** [comment]
Ok, thank you for your reply！
